services:
  - type: web
    name: mt-test-zscore
    env: python
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    autoDeploy: true
